[package]
name = "Sunflower"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version="0.14.0", features=["highlighter"] }
iced_aw = { version="0.13.0", features=["tab_bar", "menu", "card"] }
rfd = "0.16.0"
serde = { version="1.0.228", features=["derive"] }
toml = "0.9.10"
